services:
  spark-master:
    image: bitnami/spark:3.5.1
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - ./conf/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./app:/home/jupyter/app

  spark-worker:
    image: bitnami/spark:3.5.1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
    volumes:
      - ./conf/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./app:/home/jupyter/app

  jupyter-local:
    build: .
    command: python -m jupyterlab --ip "0.0.0.0" --no-browser --NotebookApp.token=''
    ports:
      - 8888:8888
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - HOME=/home/jupyter
    volumes:
      - ./app:/home/jupyter/app
      - ./conf:/home/jupyter/conf

  airflow:
    image: bitnami/airflow:2
    restart: always
    environment:
      - AIRFLOW_PASSWORD=airflow
      - AIRFLOW_USERNAME=airflow
      - AIRFLOW_FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=airflow
      - AIRFLOW_DATABASE_USERNAME=airflow
      - AIRFLOW_DATABASE_PASSWORD=airflow
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/bitnami/airflow/dags
      - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
      - AIRFLOW__WEBSERVER__WORKERS=2
    ports:
      - 8081:8080
    depends_on:
      - airflow-db
      - redis
    volumes:
      - ./airflow/dags:/opt/bitnami/airflow/dags
      - ./airflow/logs:/opt/bitnami/airflow/logs
      - ./airflow/plugins:/opt/bitnami/airflow/plugins

  airflow-db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=airflow
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
    volumes:
      - airflow-db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - 6379:6379

volumes:
  airflow-db-data:
